import fs from 'node:fs';
import path from 'node:path';
const dir=path.dirname(new URL(import.meta.url).pathname).replace(/^\/(\w:)/,'$1');
const read=n=>JSON.parse(fs.readFileSync(path.join(dir,n),'utf8'));
const write=(n,v)=>fs.writeFileSync(path.join(dir,n),typeof v==='string'?v:JSON.stringify(v,null,2));
const shell=read('shell-trigger-ledger.json'), editor=read('editor-trigger-ledger.json');
const names=shell[0].checks.map(c=>c.check);
const map=[0,1,2,3,4,5,6,7,8,9,10,11,12,[13,14,15,16,17,18],19,20,21,22,23,[24,25]];
const surfaces=shell.map(s=>({...s,checks:s.checks.map(c=>({...c}))}));
for(const s of editor){const checks=names.map(check=>({check,status:'NOT VERIFIED',evidence:s.checks[0].evidence,scope:'No complete runtime check.',needs:'R1–R3 in report section 8.'}));s.checks.forEach((c,i)=>{for(const j of [map[i]].flat()){checks[j]={...c,check:names[j]};if(Array.isArray(map[i])&&c.status!=='N/A'){checks[j].status='NOT VERIFIED';checks[j].scope='Composite provision; each individual outcome remains untested.';checks[j].needs='R2 per-cause dismissal or R3 announcement check.';}if(i===13&&c.status==='FAIL'&&j===17&&c.evidence.includes('no window blur'))checks[j]={...c,check:names[j]};}});surfaces.push({...s,checks});}
const add=(surface,group,evidence)=>{const s={surface,group,checks:names.map(check=>({check,status:'NOT VERIFIED',evidence,scope:'Implementation inventoried; full behavior matrix not run.',needs:'R1–R3 in report section 8.'}))};surfaces.push(s);return s;};
[
['Architecture templates dialog',8,'src/CreateBoardDialog.tsx:27'],['Import Mermaid dialog',8,'src/CreateBoardDialog.tsx:27'],
['Architecture template select',1,'src/CreateBoardDialog.tsx:29'],['Mermaid import file chooser',16,'src/CreateBoardDialog.tsx:36'],
['Mermaid preview zoom controls',20,'src/BoardPreview.tsx:31'],['Sidebar note/folder native reorder',14,'src/useSidebarDrag.ts:65'],
['Sidebar folder transfer',14,'src/useSidebarDrag.ts:44'],['External file drop/import',14,'src/useFileDrop.ts:34'],
['Editor image drop/paste',14,'src/NoteEditor.tsx:91; src/ImageBlock.ts'],['Image resize',17,'src/ImageBlockView.tsx:60'],
['Appearance Light/Dark/System segments',15,'src/AppearanceSettings.tsx'],['Appearance Small/Medium/Large segments',15,'src/AppearanceSettings.tsx'],
['Appearance text-size range',15,'src/AppearanceSettings.tsx'],['Windows startup switch',15,'src/StartupSettings.tsx:51'],
['Board role segments/Snap toggle',15,'src/BoardEditor.tsx:278'],['Notebook/backup browser download',16,'src/storage.ts:48; src/App.tsx:475'],
['Desktop notebook/backup save dialog',16,'src/storage.ts'],['Excalidraw main menu',20,'src/BoardEditor.tsx:295; board-main-menu-runtime.json'],
['Excalidraw More tools overlay',20,'src/BoardEditor.tsx:295'],['Native image context menu',4,'src/ImageBlockView.tsx:108'],
['Native editable title context menu',4,'src/App.tsx:1162'],['Save progress and persistent save error',11,'src/useWorkspace.ts:78; src/App.tsx:1364'],
['Loading/load-error/empty notebook state',11,'src/App.tsx:703-714,1355'],['Backup reminder and backup status',11,'src/SettingsContent.tsx:58'],
['Sidebar 1/50/187/500-item list',18,'src/App.tsx:980-1095'],['Settings Backup import/export controls',16,'src/SettingsContent.tsx'],
].forEach(a=>add(...a));
const set=(surface,index,status,evidence,scope='Source confirmed; full platform/environment matrix remains unverified.')=>{const s=surfaces.find(s=>s.surface===surface);if(!s)throw Error(surface);s.checks[index]={check:names[index],status,evidence,scope,needs:status==='NOT VERIFIED'?'R1–R3 in report section 8.':''};};
set('Native title tooltips',5,'N/A','Native tooltip is supplementary text, not a focus destination.','A tooltip must leave focus on its trigger; keyboard-visible presentation remains a separate FAIL.');
// Parent observations supersede source-only suspicions. Do not generalize one browser state to every native state.
set('Filter All items',7,'FAIL','select-focus.jpg; contrast-measurements.json; src/styles.css:2206','Browser: arrow focus on an unselected option; contrast failure in both themes.');
set('Keyboard shortcuts',5,'FAIL','Dialog.tsx:27-61; Settings→About→Keyboard shortcuts left activeElement=BODY.','Browser reproduced. Subsequent Tab returned inside; no keyboard trap escape was reproduced.');
for(const s of surfaces.filter(s=>[8,9].includes(s.group)&&!s.surface.includes('Excalidraw'))){set(s.surface,6,'NOT VERIFIED','src/Dialog.tsx:38-52; App.tsx:886,1379; dialog-runtime.json','No explicit background-inert mechanism; aria-modal/backdrop provisions exist. Actual keyboard containment and Narrator/NVDA background traversal require testing; DOM presence alone is not a reproduced escape.');}
for(const s of ['Permanent delete note','Permanent delete board','Remove folder']){set(s,5,'FAIL','src/Dialog.tsx:27-31; dialog-runtime.json','Browser delete dialog focuses Close dialog rather than Cancel.');set(s,20,'NOT VERIFIED','dialog-runtime.json','Delete Cancel returned to Note options in observed browser flow; do not propagate earlier source-only lost-focus suspicion.');}
set('Excalidraw main menu',23,'FAIL','board-main-menu-runtime.json; board-minimum.jpg','Browser accessibility snapshot exposes an unnamed button; icon is aria-hidden.');
set('Sidebar note/folder native reorder',6,'FAIL','src/useSidebarDrag.ts:65-95; src/App.tsx:651-689,1016-1078','Keyboard reorder exists; no equivalent non-drag single-pointer reorder command (WCAG 2.5.7).');
for(const s of ['Sidebar resize handle','Reference resize handle','Image resize'])set(s,6,'FAIL','src/PanelResize.tsx:118-139; src/ImageBlockView.tsx:60-124','Keyboard resize/reset exists; pointer alternatives do not offer equivalent intermediate resize outcomes (WCAG 2.5.7).');
set('Sidebar 1/50/187/500-item list',10,'FAIL','dark-large-850.jpg; runtime-measurements.json','Browser Large at 850×600: sidebar list measured 17.1px including padding. Other item-density/scaling combinations remain untested.');
set('Native editor text/link/code context menu',13,'NOT VERIFIED','src/SelectionColors.tsx:37-44; src/NoteEditor.tsx:73','Empty/code selection exclusions exist; native clipboard/spellcheck and link follow need WebView2 testing. Selected ordinary text handled separately.');
set('Selected-text context palette (right click / Shift+F10)',23,'PASS','corrected-selection-colors.spec.ts; corrected-tests.log; selection-final-retest.log','Browser: named Selection colors dialog and named swatches. Narrator announcement is separate and untested.');
set('Selection colors palette (toolbar)',23,'FAIL','src/NoteEditor.tsx:287-288','Named trigger lacks aria-expanded/haspopup/controls; source confirmed.');
set('Selection colors palette (toolbar)',16,'FAIL','src/NoteEditor.tsx:46; src/SelectionColors.tsx:23-31','Toolbar command opens rather than re-click toggling closed.');
set('Brand-logo virtualized list',25,'FAIL','src/BrandLogoPicker.tsx:99','Result count is a plain paragraph with no live-region count announcement. Actual screen reader speech NOT VERIFIED.');
set('Brand-logo virtualized list',10,'NOT VERIFIED','board-retest.log; src/BrandLogoPicker.tsx:12,58','Keyboard/logo insertion checks pass in selected browser tests; full DPI/size/scroll-reopen matrix untested.');
const groupNames=['Dropdowns/selects','Split buttons','Color palettes','Context menus','Ellipsis/options menus','Ctrl+K search','Dates/metadata','Modals/dialogs','Destructive confirmations','Tooltips','Toasts/inline status','Collapsibles/tree','Rename/editable fields','Drag and drop','Settings sliders/toggles/segments','File pickers/import/export','Resizable panels','Virtualized/long lists','Hover-reveal controls','Canvas overlays'];
const specific=[
['A1.1','Long selected label has a focus-accessible full-value tooltip','FAIL','AppSelect.tsx:15-16; styles.css:2170'],
['A1.2','Last-used Highlight/Draw options survive sessions','FAIL','HighlighterTools.tsx:18-20 state is local; cross-session persistence absent'],
['A1.3','Custom/recent colors and live palette preview','FAIL','SelectionColors.tsx:73-91 exposes fixed semantic choices only'],
['A1.4','Folder/empty-sidebar/image custom context parity','FAIL','App.tsx:990-1082; ImageBlockView.tsx:108-144 lacks these custom handlers'],
['A1.5','Sidebar menu matches active-item menu','FAIL','App.tsx:667-689 versus :1210-1267'],
['A1.6','Arrow/Enter/Ctrl+Enter/Esc-clear search behavior','FAIL','App.tsx:363-367,901-909; browser query persisted after Escape'],
['A1.7','Created date display and modified tooltip are intentional','PASS','App.tsx:1182-1189; metadata is display-only; date-picker behavior N/A'],
['A1.8','Unsaved folder/Mermaid draft dismissal policy','FAIL','Dialog.tsx:34-36,65-66; CreateBoardDialog.tsx:27; App.tsx:1507-1509'],
['A1.9','Specific folder name/count in confirmation','FAIL','App.tsx:1527-1546'],
['A1.10','Keyboard-focus tooltip and described-by relationship','FAIL','Native title attributes only on toolbar; missing tooltip on some icon controls'],
['A1.11','Routine 4–6s/error persistence/pause and recovery','FAIL','App.tsx:191-194,1449-1453'],
['A1.12','Folder disclosure persistence and hover expansion','FAIL','App.tsx:83-85; useSidebarDrag.ts:54 expands only after commit'],
['A1.13','Image caption Escape cancels draft','FAIL','ImageBlockView.tsx:126-127 persists every change and Escape closes'],
['A1.14','Structural Undo after reorder/transfer','FAIL','useSidebarDrag.ts:44,65; App.tsx:215'],
['A1.15','Live value/preview and native disabled reason','NOT VERIFIED','AppearanceSettings.tsx; StartupSettings.tsx:51; complete state walks not run'],
['A1.16','Board export busy/duplicate guard','FAIL','BoardEditor.tsx:206-211,249-256,311-312'],
['A1.17','Pointer/keyboard widths persist across reload','PASS','browser-tests.log: sidebar-resize/reference-resize passing scenarios; native outcomes separate'],
['A1.18','Logo scroll offset survives reopen','FAIL','BrandLogoPicker.tsx:32,52 starts/reset scroll state; picker conditionally mounts'],
['A1.19','Hover-revealed row controls reserve layout','FAIL','styles.css:2393-2395 adds 69px title padding on hover/focus'],
['A1.20','All engine overlay collision/shortcut combinations','NOT VERIFIED','BoardEditor.tsx:291-300; board-context subset passes, complete engine inventory still needs R2/R3'],
].map(([id,check,status,evidence])=>({id,check,status,evidence,scope:status==='PASS'?'Only the explicitly stated provision/test scenario passes.':'Source/browser scoped; no implied whole-platform result.',needs:status==='NOT VERIFIED'?'R1–R3/R7 in report section 8.':''}));
const sections={};
const entries=(section,rows)=>sections[section]=rows.map(([check,status,evidence],i)=>({id:`${section}-${i+1}`,check,status,evidence,scope:'Code/selected browser evidence only; untested subconditions remain open.',needs:status==='NOT VERIFIED'?'See R1–R10 in report section 8.':''}));
entries('B',[
['Purpose','FAIL','AnimatedIcon.tsx repeated decorative hover/focus icon motion; missing exits'],['Duration tokens','FAIL','styles.css 100/160/170/180/200/230ms literals, AnimatedIcon 450ms'],['Easing','NOT VERIFIED','UI uses ease/default ease; physics switch exists; all rendered paths not measured'],['Performance at Large and 187+ notes','NOT VERIFIED','No FPS/layout-thrash profile; grid columns/gap animate layout'],['Exit animations','FAIL','Conditional action/dialog unmount has no exit presence'],['Interruptibility','NOT VERIFIED','Focus tests pass final semantic state, no frame/velocity recording'],['Choreography','NOT VERIFIED','No intermediate-frame geometry evidence'],['All named transition paths','NOT VERIFIED','Motion table in report; source provisions differ by surface'],['Loading delay/announcements/startup frames','NOT VERIFIED','No cold-start frame capture'],['Reduced motion','NOT VERIFIED','CSS global suppression and JS matchMedia observer proven; full engine/native traversal absent'],['Click latency/progress >1 second','FAIL','Board export no in-flight state; exact latency unmeasured']]);
entries('C',[
['Visible 2px/3:1 focus on every control','FAIL','Select focus 1px inset line: 1.07–1.45:1; select-focus.jpg'],['Focus ring clipping/doubling','NOT VERIFIED','No all-control zoom traversal'],['Pressed distinct from hover','PASS','styles.css:180-189 immediate active background/1px press provision'],['Toggle pressed visual/ARIA state','NOT VERIFIED','Sidebar/Reference/Focus/tool state provision exists; all engine/toolbar states not inspected'],['Cursor correctness','NOT VERIFIED','CSS pointer/text/resize/grab provisions; full controls unmeasured'],['Selection in content/chrome','NOT VERIFIED','Selection-color tests pass selected text; full chrome/native selection untested'],['Double/rapid click safety','FAIL','Board export has no busy ref or duplicate submission guard']]);
entries('D',[
['Type scale/secondary minimum','FAIL','styles.css:860,863,2142 has base 11px secondary hints'],['Spacing/baselines','NOT VERIFIED','No exhaustive 4/8 grid/baseline measurement'],['Semantic colors/text/UI contrast','FAIL','Measured select focus contrast fails; sampled muted text and semantic color pairs pass'],['Elevation in both themes','NOT VERIFIED','Screenshots/source tokens inspected; all nested overlay depths not tested'],['One icon set/name/alignment','FAIL','AnimatedIcon uses animateicons alongside Phosphor; engine unnamed main menu'],['Density at 1/50/500 and international titles','NOT VERIFIED','Only fresh notebook and standard fixture density observed'],['Same-action consistency','FAIL','Sidebar vs active options divergence; browser export wording'],['Light/dark third-party/artwork parity','NOT VERIFIED','Logo/theme subset tests pass; all authored SVGs/backgrounds untested']]);
entries('E',[
['Minimum window without overlapping/clipped content','FAIL','850×600 Large sidebar scroll area 17.1px; Reference overlay at Medium'],['1280/1920/ultrawide/maximized/snapped','NOT VERIFIED','Browser geometry checked 1280×720,1920/2560×1080; native snapped/maximized untested'],['Windows scaling × app sizes','NOT VERIFIED','Browser Small/Medium/Large both themes sampled at 850/1280; OS DPI untested'],['Collapse priority/readable editor width','FAIL','styles.css:1867-1887 overlays Reference; 679.2px wide content at1920/2560 is separately observed'],['Chrome budget','FAIL','Conservative note lower bound27.33/28.97/31.57% at850×600; board Medium25.08%'],['Sticky toolbar/title scrolling','NOT VERIFIED','Source flex editor scroll/sticky provisions; long scrolling capture absent'],['Windows titlebar/Snap/current action','FAIL','Static Maximize window label after maximize source; native drag/Snap untested']]);
entries('F',[
['Full keyboard/tab/landmark flow','NOT VERIFIED','Selected menu/dialog/color/resize tests pass; complete installed-app walk absent'],['Landmarks/headings/note title h1','FAIL','App.tsx:1162 title textarea; runtime active note has no h1 equivalent'],['Every accessible name','FAIL','board-main-menu-runtime.json unnamed engine main-menu button (4.1.2)'],['24px minimum/44px preferred touch targets','NOT VERIFIED','Full bounding-box/spacing-exception census unmeasured'],['Non-drag single-pointer alternatives','FAIL','Sidebar reorder/panel/image resize have keyboard alternatives but missing pointer outcome equivalents (2.5.7)'],['No color-only information','NOT VERIFIED','Save uses text; selected checks exist; all canvas/export/error indicators not walked'],['Forced colors','NOT VERIFIED','No Windows High Contrast capture'],['200% zoom/text scaling','NOT VERIFIED','App sizes sampled; browser zoom/OS text scale combinations absent'],['Narrator/NVDA pass','NOT VERIFIED','No speech/traversal session'],['Associated/recoverable errors','NOT VERIFIED','Several role=alert provisions; native failure injection and field association walk absent']]);
entries('G',[
['First-run empty state','NOT VERIFIED','seed.ts welcome/new-note provisions; usefulness and empty installed notebook untested'],['Progressive disclosure/empty-section discovery','FAIL','Archive/Unfiled present; requested Trash/Pinned/Recently opened absent'],['Microcopy','FAIL','Export downloaded without completion ACK; board delete says note; generic folder confirmation'],['Truthful save/backup/storage/destructive safety','FAIL','Save ACK/recovery browser tests pass; structural reversibility missing; native failure conditions untested'],['Undo/redo scope and structure','FAIL','Tiptap text/ink history; no workspace structural Undo'],['All failures with recovery','FAIL','3s error toast has no retry; disk/PG/WebView native paths untested'],['Cold-start/switch/search timing','NOT VERIFIED','No measured latency distribution'],['Discoverable/conflict-free shortcuts','NOT VERIFIED','Cheat sheet and title hints exist; OS/engine conflict walk absent'],['Power-user command/bulk/reference paths','FAIL','CtrlK only sidebar filter; no selection/bulk item model or drag-to-reference target']]);
const tally=checks=>{const r={items:checks.length,PASS:0,FAIL:0,'NOT VERIFIED':0,'N/A':0};for(const c of checks){if(!(c.status in r))throw Error(c.status);r[c.status]++;}return r;};
const A=surfaces.flatMap(s=>s.checks).concat(specific);
const coverage=[{section:'A',...tally(A)},...Object.entries(sections).map(([section,c])=>({section,...tally(c)})),...groupNames.map((n,i)=>({section:`A1.${i+1} ${n}`,...tally(surfaces.filter(s=>s.group===i+1).flatMap(s=>s.checks).concat(specific.filter(s=>s.id===`A1.${i+1}`)))}))];
write('coverage.json',coverage);
write('trigger-ledger.json',{reviewedCommit:'0d3fa69d168402f8bb7740547003be1aff03fcc0',date:'2026-10-04',rules:'PASS is scoped to exactly named code/test provision, never all themes/DPI/native. FAIL means a known failing subcondition. NOT VERIFIED covers every remaining subcondition. N/A requires intentional policy or absent surface.',checks:names,surfaces,specificChecks:specific});
write('checklist-ledger.json',sections);
const states=['default','hover','focus-visible','active/pressed','selected','disabled','loading','error','empty'];
const controls=[
['Shell','Toggle sidebar;Saved/Save now;Reference;Focus;Appearance;Minimize window;Maximize window;Close window;New note;New board;Search notes;Filter items;Sort items;Compact note rows;New folder;Folder disclosure;New note in folder;Folder options;Note row;Board row;Show as reference row;Actions row;Unfiled notes;Archive;Settings;Note title;Board title;Note options;Board options;Reference item select;Reference close;Resize sidebar;Resize Reference'],
['Formatting','Undo;Redo;Text style;Bold;Italic;Code block;Bullet list;Checklist;Add images;Text and background color options;Highlight primary;Highlight options;Draw primary;Draw options;Guided mode;Free mode;Auto assist;Stroke Small;Stroke Medium;Stroke Large;Stroke color swatches;Highlight selected text;Clear marker strokes;Clear drawing strokes;Return to writing'],
['Content','Text/background semantic swatches;Default text;Default background;More colors;Fewer colors;Code language;Wrap code;Copy code block;Image select;Image move handle;View image;Image options;Left resize image;Right resize image;Image caption;Actual image size;Download image;Close image preview;Align image left;Align image center;Align image right;Full image width;Move image up;Move image down;Remove image'],
['Settings/dialogs','Close dialog;Appearance tab;Startup tab;Backup & restore tab;About tab;Light;Dark;System;Size Small;Size Medium;Size Large;Text size;Note font;Reset defaults;Windows startup;Export backup;Import backup;Export notebook;Import files;Keyboard shortcuts;Done;Folder name;Create folder;Rename folder;Cancel;Remove folder;Delete permanently;Import result Done;Save retry;Load Try again;Export format choices;Copy last note'],
['Board','Insert;Architecture;Export;Architecture role segments;Architecture boundary;Snap;Brand logos;Templates;Import Mermaid;Shape library;Export drawing;Export SVG;Export PNG;Export Mermaid;Copy for Miro;Dismiss board status;Diagram direction;Show shape;Reviewed draft;Close flowchart;Download Mermaid;Copy flowchart code;Architecture template;Board create title;Mermaid flowchart code;Choose Mermaid file;Preview drawing;Create board;Preview Zoom out;Preview Fit;Preview Zoom in'],
['Logos','Search brands;Logo category;Popular;Recent;All brands;Cloud;Databases;Messaging;Logo grid item;Logo variant;Dark logo background;Add selection;Remove selection;Queue remove;Queue clear;Retry catalog;Logo Done/Stop;Insert logos'],
['Engine','Main menu;Selection;Rectangle;Diamond;Ellipse;Arrow;Line;Draw;Text;Insert image;Eraser;More tools;Library;Keep selected tool active;Hand;Engine Undo;Engine Redo;Tool/style/library/help/context-menu descendants (inventory NOT VERIFIED until R2 engine walk)'],
];
write('control-state-ledger.json',controls.flatMap(([family,list])=>list.split(';').map(control=>({family,control,states:states.map(state=>({state,status:'NOT VERIFIED',evidence:'Inventory: shell-evidence.md, editor-board-evidence.md and src/App.tsx/NoteEditor.tsx/BoardEditor.tsx.',needs:'R1 control-state capture; mark truly unavailable states N/A with reason. Known failures remain in report/trigger ledger.'}))}))));
const table=rows=>'| Section | Items tested/reviewed | PASS | FAIL | NOT VERIFIED | N/A |\n| --- | ---: | ---: | ---: | ---: | ---: |\n'+rows.map(r=>`| ${r.section} | ${r.items} | ${r.PASS} | ${r.FAIL} | ${r['NOT VERIFIED']} | ${r['N/A']} |`).join('\n');
write('coverage-table.md',table(coverage));
write('surface-inventory.md','| A1 group | Actual surface | Matrix cells | PASS | FAIL | NOT VERIFIED | N/A |\n| --- | --- | ---: | ---: | ---: | ---: | ---: |\n'+surfaces.map(s=>{const t=tally(s.checks);return `| ${s.group} | ${s.surface} | ${t.items} | ${t.PASS} | ${t.FAIL} | ${t['NOT VERIFIED']} | ${t['N/A']} |`;}).join('\n'));
console.log(JSON.stringify({surfaces:surfaces.length,A0Cells:surfaces.length*26,coverage,controls:controls.reduce((n,[,v])=>n+v.split(';').length,0)},null,2));
