// Final triage. Earlier subagent notes are evidence inputs, not the final adjudication.
export default [
['F01','Major','Select keyboard focus fails non-text contrast',
'Filter and shared AppSelect options; Light/Dark; browser Medium, default text scale.',
'Open Filter items and ArrowDown to an unselected option.',
'Outline is removed and the only inset focus border is 1px --line. Measured border contrast is 1.07:1 against hover / 1.31:1 against panel in Light, 1.28:1 / 1.45:1 in Dark. The hover fill also stays below 3:1. Evidence: select-focus.jpg, contrast-measurements.json; src/styles.css:2206-2209.',
'WCAG 1.4.11 requires the custom visual state indicator to contrast at 3:1. The brief additionally requests a 2px indicator; 2px is a project target, not a blanket AA rule.',
'Use a 2px inset --accent focus indicator on [data-highlighted], preserve the selected check, and verify accent against both adjacent fills in each theme. Add a forced-colors Highlight outline fallback.','S'],
['F02','Major','Board main-menu button has no accessible name',
'Excalidraw main-menu trigger inside BoardEditor; Dark/Medium at 850×600.',
'Navigate to the board main-menu button with keyboard or inspect its accessible name.',
'The accessibility snapshot contains a blank “button”; rendered button has no aria-label, title or text and its SVG is aria-hidden. Evidence: board-main-menu-runtime.json, board-minimum.jpg; src/BoardEditor.tsx:291-300.',
'WCAG 4.1.2 requires a programmatically determinable control name.',
'Supply “Board menu” through the supported engine MainMenu trigger customization or maintained engine patch. Assert the rendered accessible name; include expanded state and owned menu where the engine supports them.','S'],
['F03','Major','Large size consumes the sidebar note list at the minimum window',
'Notes navigation; both themes, Large app size, default text scale, 850×600 browser viewport.',
'Choose Large sizing while Sidebar is visible.',
'Sidebar scroll area is only 17.1px high including 13.2px padding: approximately 3.9px remain for rows. Creation takes 112.2px, search 48.4px, notebook controls 80px and footer 164.7px. Evidence: dark-large-850.jpg and light-large-850.jpg; src/styles.css sidebar layout.',
'E minimum-size usability and D density require usable navigation at the configured 850×600 minimum.',
'Add a short-height layout: compact creation into one row, tighten footer/navigation spacing, and let nonessential sidebar chrome scroll. Reserve at least a complete navigable row plus context, then test 96px or more of list space across app/text sizes. Preserve labels and 24px targets.','M'],
['F04','Major','Sidebar reorder has no equivalent non-drag pointer action',
'Folder and note reorder; all themes/sizes; source confirmed.',
'Attempt to reorder using a single pointer without dragging.',
'Reorder uses native drag or Alt+Up/Down. Context/ellipsis menus have no Move up/down commands for the sidebar order. Keyboard alternatives exist, but do not satisfy the separate single-pointer requirement. Evidence: src/useSidebarDrag.ts:65-95; src/App.tsx:651-689,1016-1078.',
'WCAG 2.5.7 requires an equivalent single-pointer method without dragging; keyboard support is a separate requirement.',
'Add Move up and Move down to folder/note menus, disabled at boundaries with a reason, calling the same order commits. Preserve item focus and announce the new position. Keep the existing Move to folder select for transfer.','S'],
['F05','Major','Panel resize lacks a non-drag pointer method for intermediate widths',
'Sidebar and Reference resize separators; source confirmed in all theme/size variants.',
'Try to choose an intermediate panel width without dragging.',
'Arrow/Shift+Arrow/Home/End keyboard paths and double-click reset exist; pointer users can only drag or reset to one width. Evidence: src/PanelResize.tsx:118-139,160-163.',
'WCAG 2.5.7 requires a single-pointer equivalent for the resize outcome.',
'Add a small width menu with Narrower/Wider buttons and a labeled numeric width input or clickable native range. Use the same measured bounds, persistence and reset function; expose current width in pixels.','S'],
['F06','Major','Image resize lacks an equivalent non-drag pointer width control',
'Embedded image resize handles and Image options; source confirmed.',
'Choose an intermediate image width without a drag or keyboard.',
'Pointer resizing, keyboard resizing and Full width exist, but Full width is only one endpoint and cannot reproduce intermediate widths. Evidence: src/ImageBlockView.tsx:60-95,118-144.',
'WCAG 2.5.7 requires a non-drag single-pointer equivalent.',
'Expose a labeled percentage-width field or clickable preset/step controls inside Image options using the same imageWidth validation. Commit one history step and preserve selection.','S'],
['F07','Major','Selected-text context menu removes native editing commands',
'Ordinary selected rich text in editable NoteEditor; browser Medium; native WebView content not yet inspected.',
'Select normal text, then right-click or Shift+F10.',
'SelectionColors prevents the native context menu and opens only Text colors, Background colors, reset and More colors. Cut/Copy/Paste/Spell-check are absent from this custom surface. Empty/code selections deliberately preserve native behavior. Evidence: selection-colors.jpg; src/SelectionColors.tsx:37-44,73-91.',
'A1.4 explicitly requires native text-editing commands to remain available. Ctrl+C/V shortcuts continuing to work does not restore context-menu parity.',
'Preserve the native menu for ordinary selected text and offer colors through the toolbar, or provide a supported editing menu with clipboard/spelling integration and platform limitations clearly handled. Test WebView2 clipboard permissions and spellcheck.','M'],
['F08','Major','Modals lack explicit background-inert enforcement',
'Settings, folder/delete/import/brand dialogs and image preview; all theme/size variants; DOM/source confirmed.',
'Open a modal and inspect background interaction exclusion.',
'Dialog wraps Tab only at endpoints and implements no explicit background-inert mechanism; application siblings have no inert attribute. ImagePreview has the same endpoint-only pattern. Evidence: dialog-runtime.json; src/Dialog.tsx:38-61; src/App.tsx:886,1379; src/ImageBlockView.tsx:16-30. Background DOM presence alone does not prove operability or accessibility-tree exposure: the backdrop/aria-modal can constrain some paths. Pointer reachability, background Tab escape and screen-reader traversal are NOT VERIFIED.',
'A1.8 and the ARIA APG modal-dialog pattern require background content to be inert and focus contained. Do not claim a WCAG keyboard trap from this evidence alone.',
'Centralize modal ownership, inert app siblings with restoration on close, and contain focus including focus starting outside the dialog. Treat nested portaled selects as part of the modal; do not inert the active select portal.','M'],
['F09','Major','Replacing Settings with shortcuts drops focus to the body',
'Settings → About → Keyboard shortcuts; browser Medium.',
'Activate Keyboard shortcuts from within Settings.',
'Dialog remains mounted with a mount-only focus effect while its focused content is removed; activeElement becomes BODY. Subsequent Tab enters Done inside the modal. Evidence: src/Dialog.tsx:27-61; src/App.tsx:1487; modal-focus-leak.json records the later Tab outcome, not a successful escape.',
'A0 initial focus/logical restoration and WCAG 2.4.3 focus order require an intentional focus destination on surface replacement.',
'Key the modal invocation or rerun initial-focus management on its identity; focus the shortcuts heading or Done and preserve a stable outer return owner. Test Settings→Shortcuts→close and nested select paths.','S'],
['F10','Major','Structure edits have no Undo history',
'Folder rename/removal and note/folder reorder/transfer; all variants; source confirmed.',
'Move or rename an item and use Undo.',
'Workspace mutations commit directly. Toolbar Undo is Tiptap history, with no workspace history or toast Undo action. Evidence: src/App.tsx:215,566-577,1536-1548; src/useSidebarDrag.ts:44,65; src/NoteEditor.tsx:224.',
'G requires explicit text/drawing/structure scope and Undo after move/rename. Permanent deletion must retain the project’s explicit irreversible confirmation.',
'Add bounded session history for structural operations and a named Undo action (“Undo move”). Restore order/folder names without replacing newer document edits. Keep final deletion irreversible; decide separately whether a reversible Trash stage belongs before it.','M'],
['F11','Major','Error toasts disappear before users can recover',
'Export/native command feedback; all variants; source confirmed.',
'An export or native close-protection registration fails.',
'notify replaces the previous message and clears it after 3000ms; no pause, queue, history or retry action exists. Persistent save errors are separate and remain visible. Evidence: src/App.tsx:191-194,341-349,486,1449-1453.',
'A1.11 asks for longer errors and pause/recovery; G asks for actionable failure handling.',
'Store severity/actions with each notice. Keep errors until dismissed or retried; routine success may use 5s paused on hover/focus. Bound the queue and expose the affected action. Do not convert persistent save errors into transient toasts.','M'],
['F12','Minor','Narrow Reference covers writing instead of resolving panel priority',
'Reference open beside a note; Dark/Medium, 850×600 browser viewport.',
'Open Reference at the minimum width with Sidebar visible.',
'Reference becomes a 310px absolute surface and overlaps approximately 300px of the 559.4px editor area. Evidence: reference-minimum.jpg; src/styles.css:1867-1887.',
'E requests graceful collapse of Reference before Sidebar and readable writing space; project guidance gives writing priority.',
'At the narrow breakpoint, use an explicit single-support-panel policy or collapse Reference with a clear reopen affordance. Preserve its selected item, editor instance/selection and scroll. If an overlay is retained by product decision, make it temporary and explicitly dismissible.','M'],
['F13','Minor','Minimum-window chrome exceeds the writing budget',
'Note mode both themes, Small/Medium/Large at850×600; Board Medium.',
'Compare visible writing height with topbar/toolbar/footer height.',
'Conservative note chrome lower bounds are27.33%,28.97%,31.57%; Board Medium topbar+title+toolbar is25.08%. Note title/margins are excluded, so note total is higher. Evidence: runtime-measurements.json; board-minimum.jpg. Native frame/DPI not measured.',
'E flags non-content UI above approximately25% of vertical space.',
'Use short-height density for footer/topbar/tool spacing, consolidate secondary commands into existing menus, and recompute the same clearly defined budget. Keep a stable formatting toolbar and readable document.','M'],
['F14','Minor','Search has no result-keyboard navigation or Escape-clear path',
'Sidebar Ctrl+K search; browser Medium and source all variants.',
'Search “Welcome”, then ArrowDown, Enter, Ctrl+Enter and Escape.',
'Input remains focused; query remains after Escape; no result-arrow/Enter/Ctrl+Enter handlers are present. Results remain reachable through Tab. Evidence: src/App.tsx:363-367,387-392,901-909.',
'A1.6 requests arrow navigation, Enter open, Ctrl+Enter Reference, and Escape clears then dismisses.',
'Track a highlighted result, scroll it into view, open with Enter and use the existing Reference action for Ctrl+Enter. First Escape clears; next Escape returns to writing. Do not add loading/debounce to synchronous local filtering unless measurement warrants it.','M'],
['F15','Minor','Sidebar and active-item options diverge',
'Sidebar note/board ellipsis versus active note/board options; all variants.',
'Open options for the same item in the row and document header.',
'Row actions expose Archive, Reference and Delete; active-item options also expose duplicate/move/export paths. Evidence: src/App.tsx:667-689 versus :1210-1267.',
'A1.4/A1.5 require consistent actions for the same target.',
'Build the item action descriptors once and render them in row, active-item and context surfaces. Keep irreversible Delete last with danger styling and scope exports to the targeted item.','M'],
['F16','Minor','Note/board right-click menu anchors to ellipsis rather than pointer',
'Sidebar note/board context menu; all variants; source confirmed.',
'Right-click far from the row ellipsis.',
'Handler sets the row menu owner but supplies the ellipsis anchor without the pointer point. ActionPopover supports point anchoring but this caller does not use it. Evidence: src/App.tsx:620-625; src/ActionPopover.tsx:14-22.',
'A1.4 requests cursor origin with collision flipping; ellipsis opening should remain trigger anchored.',
'Capture clientX/clientY for context invocation and pass point. For Shift+F10/Menu key use the focused row rectangle. Retain the same actions and 10px viewport clamp.','S'],
['F17','Minor','Palette grid omits spatial Left/Right navigation',
'Expanded Selection colors palette; all variants; source confirmed.',
'Navigate the three-column swatch grid with Left/Right.',
'Shared action navigation handles Up/Down/Home/End over a flat button array only. Current-color checks and aria-pressed are present. Evidence: src/ActionPopover.tsx:56-63; src/styles.css:2250; src/SelectionColors.tsx:78-85.',
'A1.3 expects swatch-grid navigation consistent with its visual rows/columns.',
'Scope a roving grid navigator to each color group: Left/Right±1, Up/Down±column count, Home/End appropriate boundary. Scroll focused cells into view and preserve clear selected versus focused state.','S'],
['F18','Minor','Palette toolbar trigger does not announce expanded state',
'Text and background color options button; all variants; source confirmed.',
'Open the palette from the toolbar.',
'Button has a name and disabled state but no aria-haspopup, aria-expanded or aria-controls. Evidence: src/NoteEditor.tsx:287-288.',
'A0 surface ownership/state semantics; APG trigger patterns.',
'Expose palette open state; add aria-haspopup="dialog", aria-expanded and a stable aria-controls ID when mounted. Preserve the existing range-capture behavior.','S'],
['F19','Minor','Palette trigger re-click reopens instead of dismissing',
'Text and background color options button; all variants; source confirmed.',
'Click the toolbar trigger while its palette is already open.',
'Toolbar calls the open callback; SelectionColors unconditionally sets a new popup. Evidence: src/NoteEditor.tsx:46; src/SelectionColors.tsx:23-32.',
'A0 trigger re-click dismissal and predictable reversal.',
'Use an explicit toggle command tied to the same palette owner. Close semantically immediately and restore editor focus/range; rapid reopen may retarget any presence animation.','S'],
['F20','Minor','Action popovers lack window-blur dismissal',
'Shell/tool/image/board action popovers; all variants; source confirmed.',
'Switch to another window while the popover is open.',
'Effect registers resize, pointerdown, scroll and owner events, but no window blur listener. Evidence: src/ActionPopover.tsx:29-47. Actual WebView blur timing is NOT VERIFIED.',
'A0 asks nonmodal surfaces to dismiss on window blur.',
'Register window blur close and remove it on cleanup. Preserve focus in the newly active window; restore the app owner only on appropriate in-app keyboard dismissal.','S'],
['F21','Minor','Menus and dialogs unmount without an exit',
'Conditional ActionPopover/Dialog consumers; all variants; source confirmed.',
'Close a menu/dialog.',
'100ms opacity entry is declared but surfaces are removed immediately on close. Legacy 200ms modal keyframes are overridden later. Evidence: src/styles.css:2183,2274-2279; src/App.tsx:1456; src/SelectionColors.tsx:72.',
'A0/B ask80–150ms exits; AGENTS requires immediate semantic dismissal and live reversal.',
'Retain a noninteractive exiting shell for100ms opacity, restore focus immediately, and retarget live opacity on reopen. Under reduced motion remove instantly. Do not tie mutations or saves to completion.','M'],
['F22','Minor','Destructive confirmation initially focuses Close instead of Cancel',
'Delete note/board and Remove folder dialogs; browser note deletion confirmed, other callers source confirmed.',
'Open the destructive confirmation.',
'Dialog chooses the first available button, the header Close control. Cancel closes safely and returned focus to Note options in the observed browser flow. Evidence: dialog-runtime.json; src/Dialog.tsx:27-31,72-83; src/App.tsx:1529-1576.',
'A1.9 requests Cancel default focus; APG recommends least-destructive initial focus where appropriate.',
'Pass initialFocus pointing to Cancel on destructive dialogs. Keep Delete danger styled and require ordinary activation; no automatic confirmation on press.','S'],
['F23','Minor','New/rename folder initially focuses Close instead of the field',
'New folder/Rename folder modal; source confirmed.',
'Open a folder editing dialog.',
'Callers pass no initialFocus and Dialog selects header Close; rename has no select-all-on-entry. Evidence: src/Dialog.tsx:27-31; src/App.tsx:1495-1520.',
'A0 appropriate entry focus and A1.13 select-all on rename entry.',
'Pass the folder input as initialFocus and select its existing name for Rename. Keep field label and maxLength80; announce length/validation where needed.','S'],
['F24','Minor','Unsaved folder draft closes without a discard policy',
'Folder create/rename dialogs; source confirmed.',
'Edit the name, then press Escape, Close or click the backdrop.',
'All paths call onClose and remove the uncommitted field value without a dirty-draft guard. Evidence: src/Dialog.tsx:34-36,65-66; src/App.tsx:1507-1509.',
'A1.8 requests an explicit unsaved-flow policy; avoid confirm fatigue for unchanged drafts.',
'Track whether the local name differs from its initial value. Preserve the draft on accidental outside click or present Discard/Keep editing only for a dirty draft. Escape behavior must remain immediate and documented.','S'],
['F25','Minor','Mermaid creation draft closes without preservation or discard confirmation',
'Import Mermaid/Architecture templates create dialog; source confirmed.',
'Edit source/title then dismiss.',
'Dialog receives unconditional onClose; local code/title/preview state disappears on unmount. Conversion request tokens correctly ignore late results, but do not preserve drafts. Evidence: src/CreateBoardDialog.tsx:15-27,50-52.',
'A1.8 unsaved import flows require an explicit policy.',
'Keep a session draft by mode or guard dismissal when source/title changed. Preserve token cancellation, and never create the board from a cancelled conversion.','M'],
['F26','Minor','Folder-removal wording omits the folder name and affected count',
'Remove folder confirmation; all variants; source confirmed.',
'Remove a populated folder.',
'Generic explanation does not identify the folder/count. Notes are moved to Unfiled rather than deleted. Evidence: src/App.tsx:1527-1546.',
'A1.9 requires specific named/count wording.',
'Use “Remove ‘Folder name’?” and “Move N notes and boards to Unfiled. Their content stays intact.” Keep Cancel first and danger action last.','S'],
['F27','Minor','Board deletion uses note terminology',
'Permanent-delete board dialog/toast; all variants; source confirmed.',
'Delete a board from its options.',
'Shared confirmation and feedback use note wording for board items. Evidence: src/App.tsx:1470,1569.',
'G consistent note/board terms and A1.9 target-specific confirmation.',
'Derive item kind and title once for dialog, confirm button and result notice. Preserve the irreversible warning.','S'],
['F28','Minor','Image caption Escape commits instead of cancels',
'Image caption field; source confirmed.',
'Change caption then press Escape.',
'onChange calls updateAttributes immediately; Enter and Escape both close without restoring the initial caption. Evidence: src/ImageBlockView.tsx:126-127.',
'A1.13 Enter confirms/Escape cancels edit intent.',
'Edit a local caption draft, commit on Enter or an explicit blur policy, restore the captured caption on Escape, and make one undoable content transaction.','S'],
['F29','Minor','Folder disclosure state resets across sessions',
'Sidebar folder disclosure; all variants; source confirmed.',
'Collapse/expand a folder and reload.',
'openFolders starts with hardcoded work/data entries and is not persisted with workspace preferences. Evidence: src/App.tsx:83-85.',
'A1.12 requires session persistence.',
'Persist disclosure IDs in view preferences, prune removed folders and retain the seed policy for genuinely new folders. Do not modify document content.','S'],
['F30','Minor','Drag hover does not expand a collapsed destination folder',
'Native sidebar note transfer; all variants; source confirmed.',
'Drag a note over a collapsed folder and pause.',
'Folder opening occurs on commit, not during hover; no hover-open timer exists in the drag hook. Evidence: src/useSidebarDrag.ts:54,120-156.',
'A1.12/A1.14 requests drag-hover auto-expand.',
'Use a cancellable roughly600ms hover timer on valid folder targets, clear it on leave/drop/Escape/blur, and retain native drag behavior and exact insertion-slot hit testing.','S'],
['F31','Minor','Hover-revealed actions change title geometry',
'Sidebar note/board rows; all variants; source confirmed.',
'Hover or focus within a row.',
'Title right padding jumps from9px to78px when controls appear, changing available label width by69px. Focus-within and hover:none visibility support exist. Evidence: src/styles.css:2388-2409,2499-2500.',
'A1.19 requires no layout shift when actions reveal.',
'Reserve the controls column in the resting layout and animate only their opacity. Keep focus-within/touch visibility and stable pointer travel between row and buttons.','S'],
['F32','Minor','Native title tooltips do not implement the keyboard tooltip contract',
'Toolbar/sidebar/window icon controls; source confirmed; native timing unmeasured.',
'Focus an icon-only button with the keyboard.',
'Native title attributes provide pointer hints but no app-controlled focus tooltip or aria-describedby. Some folder/window/close controls have a valid aria-label but no tooltip. Evidence: src/NoteEditor.tsx:223-289; src/App.tsx:838-851,1011,1019; src/Dialog.tsx:80.',
'A1.10 requires focus presentation, shortcut text, Escape dismissal and consistent tooltip timing. This is distinct from an accessible-name failure.',
'Use one shared tooltip:500ms initial pointer delay, immediate adjacent transfer, focus-visible opening, Escape/click closing, no focus capture, and described-by for supplementary text. Keep accessible names independent.','M'],
['F33','Minor','Long select values truncate without a discoverable full label',
'AppSelect consumers, especially font/code/variant/boundary; source confirmed.',
'Choose a long label at narrow width or large text.',
'Trigger span ellipsizes; no full-value tooltip is supplied. Accessible selected text provision does not give a sighted keyboard user the clipped value. Evidence: src/AppSelect.tsx:15-16; src/styles.css:2170.',
'A1.1 requests full-label discovery on truncation.',
'Show a focus/pointer tooltip only when scrollWidth exceeds clientWidth, containing the full selected label. Preserve the field’s accessible name and value.','S'],
['F34','Minor','Logo result changes have no live count announcement',
'Brand-logo search/category/view; all variants; source confirmed.',
'Change a query/category and wait for results.',
'Result count is a plain paragraph. Listbox active descendant/position exists but is not an automatic filtered-count announcement. Evidence: src/BrandLogoPicker.tsx:99-111.',
'A1.18 requests an “n results” live announcement; WCAG 4.1.3 applies when a visual result status is updated without focus movement.',
'Expose a polite atomic status for the settled count, briefly debounce rapid typing, and distinguish loading/no-match/count. Verify actual NVDA/Narrator speech without duplicating active-item announcements.','S'],
['F35','Minor','Logo scroll position is lost on reopen',
'Brand-logo picker virtual list; source confirmed.',
'Scroll far into All brands, close, reopen.',
'Scroll state initializes/reset locally and picker conditionally mounts. Evidence: src/BrandLogoPicker.tsx:32,52; src/BoardEditor.tsx:317.',
'A1.18 requires back/reopen scroll retention.',
'Keep query/category/view/scroll offset in the board-owned picker state and restore after catalog geometry is ready. Keep fixed virtual row geometry and focused-item scroll behavior.','S'],
['F36','Minor','Board exports lack a busy state and duplicate-submit guard',
'Drawing/SVG/PNG export; all variants; source confirmed.',
'Start an export, reopen Export and start it again before generation/save resolves.',
'Async export functions have no shared exportBusy/ref/status. copyBusy only protects Mermaid clipboard work. Evidence: src/BoardEditor.tsx:206-211,249-256,311-312. Actual >1s latency has not been measured.',
'C rapid-click safety and A1.16/B progress for lengthy operations.',
'Use one export operation owner and an announced Generating/Saving status. Reject duplicate submissions synchronously and restore on cancel/failure; keep an explanation on disabled commands.','S'],
['F37','Minor','Failure toast always displays a success check',
'Shell toasts; all variants; source confirmed.',
'An export/native command produces an error notice.',
'Toast always renders Check regardless of severity. Evidence: src/App.tsx:1449-1453.',
'G/A1.11 require causal, truthful feedback; do not imply success on failure.',
'Render WarningCircle for errors and Check for acknowledged successes from an explicit severity field. Keep readable text and live-region priority appropriate.','S'],
['F38','Minor','Browser export says downloaded without completion evidence',
'Browser notebook/text export; all variants; source confirmed.',
'Request an export that may be pending/blocked/cancelled by the browser.',
'storage clicks an anchor then App says “Export downloaded.” Backup wording already says request/check Downloads. Evidence: src/storage.ts:48; src/App.tsx:481; src/backupHistory.ts:17; src/SettingsContent.tsx:59.',
'G truthful acknowledgement and consistent post-action content.',
'Use “Download requested. Check Downloads to confirm it was saved.” Keep desktop saved wording only after the native save acknowledgement.','S'],
['F39','Minor','Secondary helper text starts below the brief’s minimum',
'Highlighter mode/helper and code hints; default text scale; source confirmed.',
'Read tool/helper text without increasing the text setting.',
'Base declarations use11px. Other app type scales do not justify these one-off values. Evidence: src/styles.css:860,863,2142.',
'D specifies at least12px secondary text; this is a project readability target rather than a universal WCAG font-size rule.',
'Use a shared secondary token of12px multiplied by text scale and verify wrapping at minimum height. Do not shrink to preserve fixed-height controls.','S'],
['F40','Minor','Note title has no equivalent heading landmark',
'Active note document title; browser/source.',
'Navigate document headings.',
'Title is a textarea; the observed default note has no h1. User-authored headings may exist later, but do not label the document title. Evidence: runtime-measurements.json headings; src/App.tsx:1162.',
'F explicitly requests the note title as h1. WCAG1.3.1 requires meaningful structure, but does not mandate h1 solely by level.',
'Provide an accessible document-title heading associated with the editable title control, using a visually hidden h1 if necessary to preserve editing geometry. Avoid duplicated screen-reader text.','S'],
['F41','Minor','Maximized window still announces Maximize',
'Native custom maximize/restore button; source confirmed; native runtime NOT VERIFIED.',
'Maximize then inspect the action available.',
'Button always says “Maximize window” and uses Square although toggleMaximize restores an already maximized window. Evidence: src/App.tsx:843.',
'Windows action-label convention requires the current available action to be accurately named. Do not treat this static label alone as a proven standalone WCAG4.1.2 failure without checking the exposed state/value.',
'Derive Restore window/Maximize window and the matching regular-weight glyph from maximized state. Retest actual Snap Layout hover and Narrator separately.','S'],
['F42','Minor','Icon family and routine decorative animation violate project consistency',
'App shell/editor AnimatedIcon alongside Phosphor controls; source confirmed.',
'Hover/focus routine writing controls.',
'AnimatedIcon imports Lucide animateicons while other controls use Phosphor; duration is450ms on hover/focus. Reduced-motion handling exists, but the animation is decorative rather than a changed action state. Evidence: src/AnimatedIcon.tsx:1-45,100; src/App.tsx:3.',
'AGENTS requests regular-weight Phosphor; D one icon set; B causal motion.',
'Use existing regular-weight Phosphor for routine controls and preserve immediate background press feedback. Retain animated feedback only where it conveys a specific state transition.','M'],
['F43','Minor','Disabled tool actions omit explanatory reasons',
'Highlight selected text and Copy for Miro disabled commands; source confirmed.',
'Open options with no eligible text or unsupported board conversion.',
'Buttons are disabled but give no targeted reason for the unavailable action. Keyboard navigation skips them correctly. Evidence: src/HighlighterTools.tsx:94; src/BoardEditor.tsx:314.',
'A0 disabled states must explain why; A1.15 uses installed-app reasons as the existing model.',
'Supply adjacent or tooltip help: “Select editable text first” and the actual unsupported-conversion reason. Link with aria-describedby; do not put explanations only on an unfocusable disabled element.','S'],
['F44','Nit','Duplicate folder names have no inline distinction',
'Folder create/rename; source confirmed; product allowance unresolved.',
'Submit a name already used by another folder.',
'Submit trims/nonempty-checks only; no duplicate feedback or disambiguation exists. Evidence: src/App.tsx:566-577.',
'A1.13 requests duplicate-name validation; duplicate names may be an intentional product capability.',
'[NEEDS INPUT] Decide whether duplicates are allowed. If disallowed, show an associated inline error and retain focus/draft; if allowed, document the policy and disambiguate destinations where necessary.','S'],
];
